CREATE DATABASE my_project;

USE my_project

SELECT * 
FROM dbo.customer_behaviour_analysis


-- BUSINESS INSIGHTS QUESTIONS 

-- 1. WHICH CATEGORY GENERATES HIGHEST REVENUE ? 

SELECT category,
ROUND(sum(purchase_amount),2) as total_revenue
FROM dbo.customer_behaviour_analysis
GROUP BY category
ORDER BY total_revenue DESC

-- ? BUSINESS PROBLEM :- COMPANY DOES NOT KNOW WHICH CATEGORY CONTRIBUTES MOST TO REVENUE.

-- IMPACT :-  1. HELPS PRIORITIZE HIGH - PERFORMING CATEGORIES 
--            2. OPTIMIZE INVENTORY PLANNING 
--            3. IMPROVES MARKETING ROI 

-- ===========================================================================================================================================

-- QUESTION 2 : ARE DISCOUNTS ACTUALLY INCREASING PURCHASING VALUE ? 

SELECT discount_applied,
ROUND(sum(purchase_amount),2) as total_revenue,
ROUND(AVG(purchase_amount),2) AS Avg_purchase
FROM dbo.customer_behaviour_analysis
GROUP BY discount_applied
ORDER BY total_revenue DESC

-- ? BUSINESS PROBLEM : DISCOUNTS MAY REDUCE PROFIT WITHOUT INCREASING SALES.

-- IMPACT :-    1.Identify effectiveness of discount.
--              2.REDUCE UNNECESSARY DISCOUNT COSTS
--              3. IMPROVE PROFIT MARGINS.  

--======================================================================================================================================================

-- QUESTION 3. WHAT IS THE TOTAL REVENUE GENERATED BY MALE AND FEMALE CUSTOMER ?

SELECT gender,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM dbo.customer_behaviour_analysis
GROUP BY gender
order by total_revenue desc


-- ? BUSINESS PROBLEM :- LACK OF UNDERSTANDING OF REVENUE CONTRIBUTION BY GENDER SEGMENTS.

-- IMPACT : 1. HELPS DESIGN TARGETED MARKETING CAMPAIGNS. 
--          2. IMPROVES CUSTOMER SEGMENTATION STRATEGY.
--          3. ENHANCES PERSONALIZATION EFFORTS  


--======================================================================================================================================================

-- QUESTION 4. WHICH CUSTOMER USED A DISCOUNT BUT STILL SPENT MORE THAN AVERAGE PURCHASE AMOUNT ?

SELECT TOP 10 
customer_id,
discount_applied,
purchase_amount
FROM dbo.customer_behaviour_analysis
WHERE discount_applied = 'yes' AND purchase_amount > ( SELECT AVG(purchase_amount) FROM dbo.customer_behaviour_analysis)

-- ? BUSINESS PROBLEM : COMPANY CANNOT IDENTIFY HIGH - SPENDING CUSTOMERS WHO ARE ALSO DISCOUNT USERS.

-- IMPACT :-   1.IDENTIFY PREMIUM DISCOUNT - SENSITIVE CUSTOMERS.
--             2.Enables targeted discount campaigns
--             3.IMPROVES CUSTOMER RETENTION AND REVENUE. 

--======================================================================================================================================================

-- QUESTION 5. WHICH ARE THE TOP/BOTTOM 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING.

-- TOP 5 PRODUCTS
SELECT TOP 5 
item_purchased,
ROUND(avg(review_rating),2) as avg_review_rating
FROM dbo.customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_review_rating DESC

-- BOTTOME 5 PRODUCTS
SELECT TOP 5 
item_purchased,
ROUND(avg(review_rating),2) as avg_review_rating
FROM dbo.customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY avg_review_rating ASC

-- ? BUSINESS PROBLEM :- NO VISIBILITY INTO PRODUCT PERFORMANCE BASED ON CUSTOMER SATISFACTION.

-- IMPACT :-  1.PROMOTES HIGH - PERFORMING PRODUCTS.
--            2.IMPROVES LOW- RATED PRODUCTS
--            3. ENHANCES CUSTOMER EXPERIENCE   

--======================================================================================================================================================

-- QUESTION 6. AVERAGE PURCHASE : STANDARD VS EXPRESS SHIPPING.

SELECT shipping_type,
COUNT(DISTINCT customer_id) as order_placed,
ROUND(AVG(purchase_amount),2) as avg_purchase,
ROUND(Sum(purchase_amount),2) as total_revenue
FROM dbo.customer_behaviour_analysis
--WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
ORDER BY avg_purchase DESC

-- ? BUSINESS PROBLEM : UNCLEAR IF FASTER SHIPPING LEADS TO HIGHER SPENDING.

-- IMPACT : 1.HELPS OPTIMIZE SHIPPING PRICING STRATEGY.
--          2. ENCORAGES PREMIUM SHIPPING ADOPTION.
--          3. INCREASES AVERAGE ORDER VALUE.   

--======================================================================================================================================================

-- QUESTION 7. 
-- DO SUBSCRIBED CUSTOMERS SPEND MORE ? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBED AND NON - SUBSCRIBERS. 

SELECT subscription_status,
count(customer_id) as users, 
ROUND(AVG(purchase_amount),2) as average_spend,
ROUND(sum(purchase_amount),2) as total_revenue
FROM customer_behaviour_analysis
GROUP BY subscription_status
ORDER BY average_spend desc ,total_revenue DESC,users DESC

-- ? BUSINESS PROBLEM : THE EFFECTIVENESS OF SUBSCRIPTION PROGRAMS IN UNKNOWN.

-- IMPACT : 1.VALIDATES SUBSCRIPTION MODEL PROFERMANCE.
--          2. IMPROVES CUSTOMER LOYALTY PROGRAMS
--          3. INCREASES CUSTOMER LIFETIME VALUE (CLV)    

-- QUESTION 8. TOP 5 PRODUCTS WITH THE HIGHEST DISCOUNT USAGE % .

SELECT 
TOP 5
item_purchased,
count(item_purchased) as total_number_of_times_sold,
count(CASE WHEN discount_applied='Yes' THEN 1 END) AS Number_of_times_sold_when_discount_applied,
count(CASE WHEN discount_applied='Yes' THEN 1 END) * 100.0 / count(*) as discount_percent
FROM dbo.customer_behaviour_analysis
GROUP BY item_purchased
ORDER BY discount_percent DESC

-- ? BUSINESS PROBLEM :- SOME PRODUCTS MAY B E OVERLY DEPENDENT ON DISCOUNTS.

-- IMPACT : 1.IDENTIFIES DISCOUNT - DRIVEN PRODUCTS.
--          2.HELPS OPTIMIZE PRICING STRATREGY
--          3.REDUCES PROFIT MARGIN LOSS 

-- ==================================================================================================================

-- QUESTION9. 
-- SEGMENT CUSTOMER INTO NEW , RETURNING AND LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASE , 
-- AND SHOW THE COUNT OF EACH SEGMENT.
                
SELECT 
CASE WHEN previous_purchases='0' THEN 'New Customer'
     WHEN previous_purchases between 1 and 15 THEN 'Returning Customer'
ELSE 'Loyal Customers'
END AS customer_segment,
count(*) as customer_COUNT
FROM dbo.customer_behaviour_analysis
GROUP BY 
CASE WHEN previous_purchases='0' THEN 'New Customer'
     WHEN previous_purchases between 1 and 15 THEN 'Returning Customer'
ELSE 'Loyal Customers'
END

-- BUSINESS PROBLEM : LACK OF CUSTOMER SEGEMENTATION LEADS TO GENERIC STRATEGIES.

-- IMPACT : 1.ENABLES PERSONALIZED MARKETING.
--          2. IMPROVES RETENTION STRATEGIES.
--          3. INCREASES CONVERSION RATES.  

--=================================================================================================================

-- QUESTION10. WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY ?
with cte as 
(
SELECT 
category,
item_purchased,
count(item_purchased) as total_purchased,
rank() over(partition by category order by count(item_purchased) DESC) as Rn
FROM dbo.customer_behaviour_analysis
GROUP BY category,item_purchased
)

SELECT *
FROM cte
WHERE Rn <= 3

-- ? BUSINESS PROBLEM:- THE COMPANY DOESN'T KNOW TOP - PERFORMING PRODUCTS WITHIN CATEGORIES.

-- IMPACT : 1.IMPROVES PRODUCT PLACEMENT AND RECOMMENDATIONS
--          2. HELPS INVENTORY OPTIMIZATION
--          3. INCREASES SALES THROUGH BEST- SELLERS  

--===============================================================================================================

-- QUESTION11. ARE CUSTOMERS WHO ARE REPEAT BUYERS (MORE THAN 5 PREVIOUS PURCHASES) ALSO LIKELY TO SUBSCRIBE ? 

SELECT 
CASE 
     WHEN previous_purchases > 5 THEN 'Repeat Buyers'
     ELSE 'Normal Buyers'
END as customer_type,
subscription_status,
count(*) as customer_count,
count(*) * 100.0 / sum(count(*)) over(partition by case 
                                       WHEN previous_purchases > 5 THEN 'Repeat Buyers'
                                       ELSE 'Normal Buyers'  
                                       END
                                       ) as percents
FROM dbo.customer_behaviour_analysis
GROUP BY 
CASE 
     WHEN previous_purchases > 5 THEN 'Repeat Buyers'
     ELSE 'Normal Buyers'
END ,subscription_status

-- ? BUSINESS PROBLEM :- UNCLEAR RELATIONSHIP BETWEEN LOYALTY AND SUBSCRIPTION.

-- IMPACT :- 1. IMPROVES SUBSCRIPTION TARGETING
--           2. INCREASES CONVERSION TO PAID PROGRAMS.
--           3. INCREASE CUSTOMER RETENTION STRATEGY.


-- 12. What is the revenue contribution of each age group ? 

SELECT 
CASE 
     WHEN age between 18 and 25 then '18-25'
     WHEN age between 26 and 35 then '26-35'
     WHEN age between 36 and 50 then '35-50'
     ELSE '51+'
END AS age_group ,
round(sum(purchase_amount),2) as total_revenue
FROM dbo.customer_behaviour_analysis
GROUP BY 
CASE 
     WHEN age between 18 and 25 then '18-25'
     WHEN age between 26 and 35 then '26-35'
     WHEN age between 36 and 50 then '35-50'
     ELSE '51+'
     END

-- ? BUSINESS PROBLEM : NO VISIBILTY INTO WHICH AGE GROUP CONTRIBUTES MOST TO REVENUE.

-- IMPACT : 1.ENABLES AGE- BASED TARGETING.
--          2. ENHANCES MARKETING EFFICENCY.